package pancer.dreams;

public class RecentDreamCard extends javax.swing.JPanel {

   private String title;
   private String fecha;
   private String categoria;
   private String[] tags;
    
    public RecentDreamCard(String title, String fecha, String categoria, String[] tags) {
        this.title = title;
        this.fecha = fecha;
        this.categoria = categoria;
        this.tags = tags;
        initComponents();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        categoryLabel = new javax.swing.JLabel();
        tag1Button = new javax.swing.JButton();
        tag2Button = new javax.swing.JButton();
        tag3Button = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        categoryLabel1 = new javax.swing.JLabel();
        tag1Button1 = new javax.swing.JButton();
        tag2Button1 = new javax.swing.JButton();
        tag3Button1 = new javax.swing.JButton();
        titleLabel1 = new javax.swing.JLabel();
        dateLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 251, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 251, 252));

        categoryLabel.setForeground(new java.awt.Color(204, 0, 204));
        categoryLabel.setText(this.categoria);
        jPanel4.add(categoryLabel);

        tag1Button.setBackground(new java.awt.Color(255, 255, 255));
        tag1Button.setForeground(new java.awt.Color(255, 204, 255));
        tag1Button.setText(this.tags[0]);
        tag1Button.setBorderPainted(false);
        jPanel4.add(tag1Button);

        tag2Button.setBackground(new java.awt.Color(255, 255, 255));
        tag2Button.setForeground(new java.awt.Color(255, 204, 255));
        tag2Button.setText(this.tags[1]);
        tag2Button.setBorderPainted(false);
        jPanel4.add(tag2Button);

        tag3Button.setBackground(new java.awt.Color(255, 255, 255));
        tag3Button.setForeground(new java.awt.Color(255, 204, 255));
        tag3Button.setText(this.tags[2]);
        tag3Button.setBorderPainted(false);
        jPanel4.add(tag3Button);

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 64, -1, -1));

        titleLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        titleLabel.setText(this.title);
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 24, -1, -1));

        dateLabel.setText(this.fecha);
        add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 24, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 251, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 251, 252));

        categoryLabel1.setForeground(new java.awt.Color(204, 0, 204));
        categoryLabel1.setText(this.categoria);
        jPanel5.add(categoryLabel1);

        tag1Button1.setBackground(new java.awt.Color(255, 255, 255));
        tag1Button1.setForeground(new java.awt.Color(255, 204, 255));
        tag1Button1.setText(this.tags[0]);
        tag1Button1.setBorderPainted(false);
        jPanel5.add(tag1Button1);

        tag2Button1.setBackground(new java.awt.Color(255, 255, 255));
        tag2Button1.setForeground(new java.awt.Color(255, 204, 255));
        tag2Button1.setText(this.tags[1]);
        tag2Button1.setBorderPainted(false);
        jPanel5.add(tag2Button1);

        tag3Button1.setBackground(new java.awt.Color(255, 255, 255));
        tag3Button1.setForeground(new java.awt.Color(255, 204, 255));
        tag3Button1.setText(this.tags[2]);
        tag3Button1.setBorderPainted(false);
        jPanel5.add(tag3Button1);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 64, -1, -1));

        titleLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        titleLabel1.setText(this.title);
        jPanel1.add(titleLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 24, -1, -1));

        dateLabel1.setText(this.fecha);
        jPanel1.add(dateLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 24, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel categoryLabel1;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton tag1Button;
    private javax.swing.JButton tag1Button1;
    private javax.swing.JButton tag2Button;
    private javax.swing.JButton tag2Button1;
    private javax.swing.JButton tag3Button;
    private javax.swing.JButton tag3Button1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    // End of variables declaration//GEN-END:variables
}
